repos:
  - name: test-repo
    repo: https://github.com/yuriy-kovalchuk/Homelab
    path: kubernetes/apps
  - name: flux-repo
    repo: https://github.com/yuriy-kovalchuk/Homelab
    path: management-cluster/fluxcd
update_type: all
