apiVersion: v1
kind: Service
metadata:
  name: {{ include "yk-update-checker.api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yk-update-checker.api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    {{- include "yk-update-checker.api.selectorLabels" . | nindent 4 }}
