{{- if and .Values.dashboard.enabled .Values.dashboard.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "yk-update-checker.dashboard.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yk-update-checker.dashboard.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "yk-update-checker.dashboard.fullname" . }}
  minReplicas: {{ .Values.dashboard.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.dashboard.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.dashboard.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.dashboard.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.dashboard.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.dashboard.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
