{{- if and .Values.dashboard.enabled .Values.dashboard.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "yk-update-checker.dashboard.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yk-update-checker.dashboard.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "yk-update-checker.dashboard.selectorLabels" . | nindent 6 }}
  {{- if .Values.dashboard.pdb.minAvailable }}
  minAvailable: {{ .Values.dashboard.pdb.minAvailable }}
  {{- else if .Values.dashboard.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.dashboard.pdb.maxUnavailable }}
  {{- end }}
{{- end }}
