# Test values for yk-update-checker
# Copy and customize for your environment, then deploy with deploy-test.sh

api:
  image:
    repository: harbor-mgmt.yuriy-lab.cloud/dev/update-checker-api
    tag: latest
    pullPolicy: Always
  verbose: true

scanner:
  image:
    pullPolicy: Always
    repository: harbor-mgmt.yuriy-lab.cloud/dev/update-checker-scanner
    tag: latest

  verbose: true
  config:
    updateType: all
    parallelChecks: 5
    repos:
      - name: Homelab
        repo: https://github.com/yuriy-kovalchuk/Homelab


dashboard:
  image:
    pullPolicy: Always
    repository: harbor-mgmt.yuriy-lab.cloud/dev/update-checker-dashboard
    tag: latest

  verbose: true
